//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Mysettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Mysettings defaultInstance = ((Mysettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Mysettings())));
        
        public static Mysettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/updatepkgs")]
        public string download_path {
            get {
                return ((string)(this["download_path"]));
            }
            set {
                this["download_path"] = value;
            }
        }
    }
}
