//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Mysettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Mysettings defaultInstance = ((Mysettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Mysettings())));
        
        public static Mysettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/downloadpkgs")]
        public string download_path {
            get {
                return ((string)(this["download_path"]));
            }
            set {
                this["download_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.25")]
        public string terminal_server_ip {
            get {
                return ((string)(this["terminal_server_ip"]));
            }
            set {
                this["terminal_server_ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string terminal_server_id {
            get {
                return ((string)(this["terminal_server_id"]));
            }
            set {
                this["terminal_server_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fangpu_datacenter")]
        public string terminal_server_db {
            get {
                return ((string)(this["terminal_server_db"]));
            }
            set {
                this["terminal_server_db"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string localdatapath {
            get {
                return ((string)(this["localdatapath"]));
            }
            set {
                this["localdatapath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D17")]
        public string devicename {
            get {
                return ((string)(this["devicename"]));
            }
            set {
                this["devicename"] = value;
            }
        }
    }
}
