//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fangpu_terminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class bandchecklist
    {
        public int idchecklist2 { get; set; }
        public string deviceid { get; set; }
        public string sn { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string position { get; set; }
        public string name { get; set; }
        public string producesn { get; set; }
        public string cardnumber { get; set; }
        public string weight { get; set; }
        public string singleweight { get; set; }
        public string materialnumber { get; set; }
        public string waste { get; set; }
        public string producttype { get; set; }
        public string remark { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> total { get; set; }
    }
}
