//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fangpu_terminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class fieldchecklist
    {
        public int idchecklist_3 { get; set; }
        public string deviceid { get; set; }
        public string producer { get; set; }
        public string type { get; set; }
        public string datetime { get; set; }
        public string material { get; set; }
        public Nullable<double> singleweight { get; set; }
        public Nullable<double> standardlength { get; set; }
        public Nullable<double> actuallength { get; set; }
        public Nullable<double> standardthickness { get; set; }
        public Nullable<double> actualthickness { get; set; }
        public Nullable<bool> burn { get; set; }
        public Nullable<bool> bubble { get; set; }
        public Nullable<bool> irregular { get; set; }
        public Nullable<bool> impurity { get; set; }
        public Nullable<bool> deformation { get; set; }
        public Nullable<bool> injure { get; set; }
        public Nullable<bool> raw { get; set; }
        public Nullable<bool> band { get; set; }
        public Nullable<bool> spot { get; set; }
        public Nullable<bool> internalfail { get; set; }
        public Nullable<bool> @double { get; set; }
        public Nullable<bool> judge { get; set; }
        public string handle { get; set; }
        public string monitorcheck { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> datetime2 { get; set; }
        public string confirm { get; set; }
        public string sn { get; set; }
    }
}
