//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fangpu_terminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class historydata
    {
        public int historydataid { get; set; }
        public string deviceid { get; set; }
        public string value { get; set; }
        public Nullable<float> shuayou_consume_seconds { get; set; }
        public Nullable<float> kaomo_consume_seconds { get; set; }
        public Nullable<float> kaoliao_consume_seconds { get; set; }
        public Nullable<float> lengque_consume_seconds { get; set; }
        public Nullable<float> jinliao_consume_seconds { get; set; }
        public Nullable<float> kaomo_temp { get; set; }
        public Nullable<float> kaoliao_temp { get; set; }
        public Nullable<float> cycletime { get; set; }
        public System.DateTime storetime { get; set; }
        public string systus { get; set; }
    }
}
