//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fangpu_terminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class historydata_jsoncopy
    {
        public int historydataid { get; set; }
        public string deviceid { get; set; }
        public string data_json { get; set; }
        public System.DateTime storetime { get; set; }
        public string systus { get; set; }
    }
}
