//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fangpu_terminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class warn_info
    {
        public int idwarn_info { get; set; }
        public string device_name { get; set; }
        public string warn_message { get; set; }
        public Nullable<System.DateTime> storetime { get; set; }
    }
}
