//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fangpu_terminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceduretechnologybase
    {
        public int idproceduretechnologybase { get; set; }
        public string device_name { get; set; }
        public string product_id { get; set; }
        public string material { get; set; }
        public Nullable<double> shuayou_base { get; set; }
        public Nullable<double> shuayou_upper { get; set; }
        public Nullable<double> shuayou_lower { get; set; }
        public Nullable<double> yurelu_temp_base { get; set; }
        public Nullable<double> yurelu_temp_upper { get; set; }
        public Nullable<double> yurelu_temp_lower { get; set; }
        public Nullable<double> kaomo_consume_base { get; set; }
        public Nullable<double> kaomo_consume_upper { get; set; }
        public Nullable<double> kaomo_consume_lower { get; set; }
        public Nullable<double> kaoliaolu_temp_base { get; set; }
        public Nullable<double> kaoliaolu_temp_upper { get; set; }
        public Nullable<double> kaoliaolu_temp_lower { get; set; }
        public Nullable<double> kaoliao_consume_base { get; set; }
        public Nullable<double> kaoliao_consume_upper { get; set; }
        public Nullable<double> kaoliao_consume_lower { get; set; }
        public Nullable<double> qigangjinliao_consume_base { get; set; }
        public Nullable<double> qigangjinliao_consume_upper { get; set; }
        public Nullable<double> qigangjinliao_consume_lower { get; set; }
        public Nullable<double> lengque_consume_base { get; set; }
        public Nullable<double> lengque_consume_upper { get; set; }
        public Nullable<double> lengque_consume_lower { get; set; }
        public Nullable<double> shangsheng_speed_base { get; set; }
        public Nullable<double> shangsheng_speed_upper { get; set; }
        public Nullable<double> shangsheng_speed_lower { get; set; }
        public Nullable<double> xiajiang_speed_base { get; set; }
        public Nullable<double> xiajiang_speed_upper { get; set; }
        public Nullable<double> xiajiang_speed_lower { get; set; }
        public Nullable<double> jinliao_consume_base { get; set; }
        public Nullable<double> jinliao_consume_lower { get; set; }
        public Nullable<double> jinliao_consume_upper { get; set; }
        public Nullable<double> hutao_length_base { get; set; }
        public Nullable<double> hutao_length_upper { get; set; }
        public Nullable<double> hutao_length_lower { get; set; }
        public Nullable<double> yemian_distance_base { get; set; }
        public Nullable<double> yemian_distance_upper { get; set; }
        public Nullable<double> yemian_distance_lower { get; set; }
        public string uniqueidentifier { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
